# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from weaksignals.analyzer.v1 import analyzer_pb2 as weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weaksignals/analyzer/v1/analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAnalysis = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/StartAnalysis',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisResponse.FromString,
                _registered_method=True)
        self.GetAnalysis = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/GetAnalysis',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisResponse.FromString,
                _registered_method=True)
        self.ListCandidates = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/ListCandidates',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesResponse.FromString,
                _registered_method=True)
        self.CancelAnalysis = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/CancelAnalysis',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisResponse.FromString,
                _registered_method=True)
        self.ScoreText = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/ScoreText',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/weaksignals.analyzer.v1.AnalyzerService/GetModelInfo',
                request_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)


class AnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartAnalysis(self, request, context):
        """Идемпотентный запуск анализа коллекции. Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysis(self, request, context):
        """Статус анализа. Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCandidates(self, request, context):
        """Кандидаты с признаками и объяснениями, постранично, стабильная сортировка по rank, затем candidate_id. Deadline 15 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAnalysis(self, request, context):
        """Кооперативная отмена. Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreText(self, request, context):
        """Прямой скоринг произвольного описания технологии (оценка на скрытом датасете организаторов, UI «проверить»). Deadline 20 s (90 s при with_enrichment). Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Сведения об активной модели и её метриках. Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAnalysis,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisResponse.SerializeToString,
            ),
            'GetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysis,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisResponse.SerializeToString,
            ),
            'ListCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidates,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesResponse.SerializeToString,
            ),
            'CancelAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAnalysis,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisResponse.SerializeToString,
            ),
            'ScoreText': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreText,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoRequest.FromString,
                    response_serializer=weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weaksignals.analyzer.v1.AnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weaksignals.analyzer.v1.AnalyzerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/StartAnalysis',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.StartAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/GetAnalysis',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/ListCandidates',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ListCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/CancelAnalysis',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.CancelAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/ScoreText',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.ScoreTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.analyzer.v1.AnalyzerService/GetModelInfo',
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoRequest.SerializeToString,
            weaksignals_dot_analyzer_dot_v1_dot_analyzer__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
