# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from weaksignals.collector.v1 import collector_pb2 as weaksignals_dot_collector_dot_v1_dot_collector__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weaksignals/collector/v1/collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCollection = channel.unary_unary(
                '/weaksignals.collector.v1.CollectorService/StartCollection',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollection = channel.unary_unary(
                '/weaksignals.collector.v1.CollectorService/GetCollection',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionResponse.FromString,
                _registered_method=True)
        self.StreamDocuments = channel.unary_stream(
                '/weaksignals.collector.v1.CollectorService/StreamDocuments',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StreamDocumentsRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.DocumentChunk.FromString,
                _registered_method=True)
        self.GetDocuments = channel.unary_unary(
                '/weaksignals.collector.v1.CollectorService/GetDocuments',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsResponse.FromString,
                _registered_method=True)
        self.CancelCollection = channel.unary_unary(
                '/weaksignals.collector.v1.CollectorService/CancelCollection',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionResponse.FromString,
                _registered_method=True)
        self.CheckEncyclopedia = channel.unary_unary(
                '/weaksignals.collector.v1.CollectorService/CheckEncyclopedia',
                request_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaRequest.SerializeToString,
                response_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaResponse.FromString,
                _registered_method=True)


class CollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartCollection(self, request, context):
        """Идемпотентный запуск сбора. Повтор с тем же idempotency_key возвращает существующую коллекцию.
        Deadline клиента: 5 s. Retry: да (UNAVAILABLE, DEADLINE_EXCEEDED), backoff 0.5 s ×2, jitter, ≤ 3 попыток.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Статус и прогресс. Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDocuments(self, request, context):
        """Потоковая выдача документов коллекции (server streaming). Deadline 120 s. Retry: да (с page_token последнего чанка).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocuments(self, request, context):
        """Пакетное получение документов по идентификаторам (≤ 200). Deadline 10 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelCollection(self, request, context):
        """Запрос отмены (кооперативная). Deadline 5 s. Retry: да (идемпотентна).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckEncyclopedia(self, request, context):
        """Индикатор зрелости: наличие статьи Wikipedia и просмотры. Deadline 10 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCollection,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionResponse.SerializeToString,
            ),
            'StreamDocuments': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDocuments,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.StreamDocumentsRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.DocumentChunk.SerializeToString,
            ),
            'GetDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocuments,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsResponse.SerializeToString,
            ),
            'CancelCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelCollection,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionResponse.SerializeToString,
            ),
            'CheckEncyclopedia': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEncyclopedia,
                    request_deserializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaRequest.FromString,
                    response_serializer=weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weaksignals.collector.v1.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weaksignals.collector.v1.CollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/StartCollection',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.StartCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/GetCollection',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/StreamDocuments',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.StreamDocumentsRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.DocumentChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/GetDocuments',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.GetDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/CancelCollection',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.CancelCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckEncyclopedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.collector.v1.CollectorService/CheckEncyclopedia',
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaRequest.SerializeToString,
            weaksignals_dot_collector_dot_v1_dot_collector__pb2.CheckEncyclopediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
