# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from weaksignals.insight.v1 import insight_pb2 as weaksignals_dot_insight_dot_v1_dot_insight__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weaksignals/insight/v1/insight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InsightServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExpandQuery = channel.unary_unary(
                '/weaksignals.insight.v1.InsightService/ExpandQuery',
                request_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryRequest.SerializeToString,
                response_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryResponse.FromString,
                _registered_method=True)
        self.GenerateInsight = channel.unary_unary(
                '/weaksignals.insight.v1.InsightService/GenerateInsight',
                request_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightRequest.SerializeToString,
                response_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightResponse.FromString,
                _registered_method=True)
        self.GetProviderStatus = channel.unary_unary(
                '/weaksignals.insight.v1.InsightService/GetProviderStatus',
                request_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusRequest.SerializeToString,
                response_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusResponse.FromString,
                _registered_method=True)


class InsightServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExpandQuery(self, request, context):
        """Расширение свободного запроса в поисковые фразы ru/en. Deadline 30 s. Retry: да (идемпотентна по query_text).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateInsight(self, request, context):
        """Генерация русскоязычного инсайта по кандидату на основе переданных доказательств. Deadline 120 s.
        Retry: да, только с тем же idempotency_key (сервер вернёт кешированный результат).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderStatus(self, request, context):
        """Состояние провайдеров LLM (для readiness и UI). Deadline 5 s. Retry: да.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExpandQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandQuery,
                    request_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryRequest.FromString,
                    response_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryResponse.SerializeToString,
            ),
            'GenerateInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInsight,
                    request_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightRequest.FromString,
                    response_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightResponse.SerializeToString,
            ),
            'GetProviderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderStatus,
                    request_deserializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusRequest.FromString,
                    response_serializer=weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weaksignals.insight.v1.InsightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weaksignals.insight.v1.InsightService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InsightService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExpandQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.insight.v1.InsightService/ExpandQuery',
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryRequest.SerializeToString,
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.ExpandQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.insight.v1.InsightService/GenerateInsight',
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightRequest.SerializeToString,
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.GenerateInsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weaksignals.insight.v1.InsightService/GetProviderStatus',
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusRequest.SerializeToString,
            weaksignals_dot_insight_dot_v1_dot_insight__pb2.GetProviderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
